services:
  - type: web
    name: youtube-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && sed -i 's/\r//' start.sh && chmod +x start.sh
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: HOST
        sync: false
      - key: HOST_SCHEME
        value: https
      - key: HOST_PORT
        value: "443"

  - type: web
    name: youtube-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
